wikimedia/ws-export

book/formats/EpubGenerator.php
I have checked on bn, ca, da, de, el, en, et, fa, fr, hy, is, it, la, nl, no, pl, pt, ro, ru, te, vec and old wikisources. Only on the plwiki the {URL} tag is used. Changing into a clickable link may increase its popularity :), and enhance “About” section usability.
=> non-clickable link for {URL} tag -> clickable one

http/toolinfo.json
De facto standard to make the tool indexable by directories like https://tools.wmflabs.org/hay/directory/
=> Add toolinfo.json

book/BookProvider.php
generate cover thumb picture if 'ws-cover' is a local oldwikisource file - avoid `cURL error 3: <url> malformed` error, see: https://tools.wmflabs.org/wsexport/tool/book.php?lang=www&page=User%3AZdzislaw%2Ftest%C5%9B%C4%87+P02&format=epub-3
=> cover thumb picture for oldwikisource local file

book/BookProvider.php, cli/book.php, cli/help/book.txt
Adding credits can add a lot of time to the book generation
process (in the order of minutes) and is not always desirable, e.g. when experimenting
with output formats or working on the tool itself.
=> CLI: make credit generation optional

.travis.yml
This automatically runs tests using [travis CI](https://travis-ci.org). You'll need to enable it on the website, they provide free services for open source projects.
See https://travis-ci.org/jberkel/tool for an example run.
=> Add travis.yml for CI builds

book/FontProvider.php, book/mediawiki.css
@Tpt, this is a better way to have the fonts in the ePub.
It doesn’t change the default typeface, since either `f_s` or `l_l` have to be defined first with `@font-face`.
Any user can make use of the typefaces defining them.
I hope this is better now and can be merged.
=> add FreeSerif and LinuxLibertine (if and only if previously defined)

book/formats/ConvertGenerator.php
`createEpub` can throw an exception, in this case, `$persistentEpubFileName` is not set, so `removeFile('')` is called and tries to remove the current directory. (yes, it fails because `rm` does not delete a directory, without `-Rf`)
=> Check if filename is set

book/PageParser.php, tests/book/PageParserTest.php, tests/book/fixtures/Tales_of_Unrest/Navigation.html, utils/Api.php
Change the chapter-finding method to use the href value of
anchors rather than the title, because linked images can set
different title text.
Bug: #146
=> Use 'href' instead of 'title' as the source of chapter links

book/PageParser.php
Some pages were throwing a PHP Notice: "Undefined index: path"
=> Check for URL path component before using

http/book.php
Looks like some exceptions had multiline messages - use the first line
in headers. Additionally, display such errors on multiple lines on screen.
Bug: https://phabricator.wikimedia.org/T221333
=> Fix "Header may not contain more than a single header" warning

http/.user.ini
While it's not a proper fix for #44, it improves the situation while
we're investigating it further. In any case, 256M is not an unreasonable
limit.
=> Double PHP memory limit

http/book.php
The code attempted to serve the form twice, setting the headers both times.
Bug: https://phabricator.wikimedia.org/T221334
=> Fix "Cannot modify header information - headers already sent"

book/Book.php, book/BookProvider.php, book/FileCleaner.php, book/Picture.php, book/formats/EpubGenerator.php, cli/cleanup.sh, utils/Api.php, utils/utils.php
When testing on https://fr.wikisource.org/wiki/Voyage_au_centre_de_la_Terre
this halved peak memory usage from 42M to 22M. Even the old version is apparently
able to fit in memory, however - so the mystery remains. After deploying this
change, we need to see how it performs because while on my laptop there's no
noticeable performance degradation, this is not necessarily the case on NFS.
References #44
Bug: https://phabricator.wikimedia.org/T221493
=> Store images on disk while generating books

.gitignore, cli/book.php, composer.json, config.dist.php, http/book.php, phpcs.xml
Move the $wsexportConfig global to a separate config.php file
and load it for the web and CLI entry points.
As this new file is not optional, also add a composer script to
create it at install and update time.
Bug: T222330
=> Move config to separate file

http/book.php, tests/http/BookTest.php, utils/utils.php
I initially considered not logging some HttpExcpetions as they're
"business as usual", but decided for now that having everything
logged is valuable and we can exclude some excpetions later if
they will be too noisy.
Bug: T221335
=> Add exception logging

.gitignore, book/CreationLog.php, config.dist.php, http/stat.php
Add a new config variable 'logDatabase' that specifies the
full filesystem path to the logs.sqlite file in which to store
access statistics.
Also switch to using the new config.php file in stats.php so
that this new variable need only be set in one place.
Ref: #168
=> Move logs.sqlite to the http directory

bin/cleanup.sh, src/BookProvider.php, src/FileCache.php, src/Generator/AtomGenerator.php, src/Generator/EpubGenerator.php, src/Refresh.php, src/Util/Util.php
Currently, wsexport attempts to clean after itself, e.g. in
Picture::__destruct(), however this doesn't protect us from
some types of fatal errors, PHP segfaults and programmer
mistakes. Since we want to keep the temporary files in local
/tmp to make I/O fast, we can't clean them up via a gronjob,
as the webservice can be run on different lighttpd VMs.
This patch introduces a new class FileCache and makes
everything use it:
* It maintains a per-tool directory under tempPath
(which is now intended to point to /tmp on Toolforge).
* Cleans this directory of old files on 5% of requests.
* Unifies all places using temporary files/directories, making
it use the new class. Util::buildTemporaryFileName() can't
override this now (and thus it can't forget files in places
FileCache doesn't clean). …
=> Rework cache operation

bin/book.php, bin/opds.php, bootstrap.php, phpunit.xml.dist, public/book.php, public/stat.php, tests/bootstrap.php
There are five entrypoints to this application: two web, two CLI,
and one test. The test one loads the others sometimes, and in
doing can have its config clobbered. This change moves all
config-loading to a single file, bootstrap.php, which can then
avoid double-loading.
=> Universal bootstrap for all entrypoints

composer.json, composer.lock, phpcs.xml
This updates Composer dependencies to their latest versions,
and removes the OneObjectStructurePerFile phpcs rule exclusion
which has been unnecessary since we moved to PSR4.
=> Update dependencies and remove an out of date phpcs exclusion

src/Generator/Epub3Generator.php, src/Refresh.php
This fixes two things that epubcheck was complaining about:
1. "Found a reference to a resource that is not a spine item."
with the ToC being referenced with `href="#toc"`, which isn't
permitted. We can't link directly to the actual content-ToC
because that's not in a standard place in Wikisource works.
2. "Referenced resource could not be found in the EPUB." with
links in the About page that are not fully qualified. Fixed
by adding the protocol and domain name.
=> Fully-qualify URLs in About page, and remove toc

src/BookProvider.php
We were using the full Content-Type header as the media-type
of epub manifest items, but this attribute is somewhat more
restricted in what it'll accept. So we discard everything after
the first semicolon.
https://phabricator.wikimedia.org/T227334
Bug: T227334
=> Sanitize images' mime types

src/CreationLog.php
The previous `WHERE n BETWEEN x AND y` was excluding the last
day of the month.
=> Fix stats retrieval to include whole month

src/CreationLog.php, tests/CreationLogTest.php
We were discarding all duplicate rows, but about 1% of data was
correct (the same ebook being generated in the same second of
time). The process is updated to check for the total counts of
duplicates and make sure they match.
Bug: T226070
=> Fix import process to handle correct duplicates

public/templates/book.php, public/templates/stat.php, src/CreationLog.php
Add a list of books popular in the last 3 months to the left side
of the main page. Also add a breadcrub link back to the main page
from the stats page.
This patch indents a bunch of lines; it's easier to see the changes if you use Github's "ignore whitespace changes" option.
=> Add recent popular books to front page

src/Util/Api.php
Allows to avoid to wait indefinitely if Wikisource servers do not respond
Closes #204
=> Adds connection and request timeouts for API requests

src/CreationLog.php
Allows to fail fast if the database server is down.
It won't make book creation fail more because the log insertion is after the output buffer flush.
Should be a good mitigation for https://phabricator.wikimedia.org/T236391
We should maybe change 2s to something different
=> Adds a timeout to SQL queries

src/Generator/ConvertGenerator.php
The PDF generation commands for ebook-convert have their own
margin-setting CLI options.
Bug: https://phabricator.wikimedia.org/T244825
=> Use pdf-page-margin-* instead of margin-* for PDF generation

src/FileCache.php
The previous glob('*.*') was only selecting files with dots in
them for cleanup. This switches to DirectoryIterator on everything
in the temp directory.
https://phabricator.wikimedia.org/T246197
Bug:T246197
=> Clear all temp files

composer.json, composer.lock, src/Cleaner/FileCleaner.php, src/Picture.php, src/Util/Util.php
Problem reported at: https://fr.wikisource.org/wiki/Wikisource:Questions_techniques#Export_pdf_%3D%3E_changement_de_format_%3F
PDF generated from pages like https://fr.wikisource.org/wiki/Le_Secr%C3%A9taire_et_le_Cuisinier could not be opened with Acrobat Reader because they use 8bits JPG images
=> Use image magic to clean up JPEG file

phpcs.xml, tests/http/StatTest.php
The HTTP tests are no longer required to run in separate processes
because they now use Symfony's KernelBrowser request system.
=> Restore MediaWiki.Commenting.PhpunitAnnotations sniff

src/BookCreator.php, src/Command/ExportCommand.php, src/Controller/ExportController.php, tests/BookCreator/BookCreatorIntegrationTest.php, tests/BookCreator/BookCreatorTest.php
Exported filenames should not contain subpage slashes. They do
actually work, at least for some browsers, but Symfony doesn't
allow them and they also mean that books exported on the CLI
are put into subdirectories (which can be a bit odd — this also
makes this a breaking change, but we've already broken the
CLI format with the change to app:export so I don't think that
matters).
This change also removes the return values from BookCreator::create()
and replaces them with other getter methods on that class. This'll
make it easier when we come to turn that class into an injectable
service.
Bug: T263577
=> Sanitize output filenames of books

config/bootstrap.php, config/services.yaml, src/CreationLog.php, tests/CreationLogTest.php, tests/Http/BookTest.php, tests/Http/StatTest.php
This is a step towards fully removing the $wsexportConfig global
variable.
The CreationLog is already a service class, so to remove the 'stat'
key, we just have to inject that value (which comes from the
APP_ENABLE_STATS environment variable) into the class, and update
the tests.
https://phabricator.wikimedia.org/T265854
=> Remove $wsexportConfig['stat']

src/Util/Api.php
Remove support for exporting from Wikibooks, and fix the domain
name of Wikilivres (although it's not currently working, that
might change), and add support for exporting from the Beta
Wikisource at en.wikisource.beta.wmflabs.org.
Bug: T266085
Bug: T259687
=> Add Beta, remove Wikibooks, and fix Wikilivres domain name

templates/base.html.twig
There used to be HTML in some error messages, but none now, so
it's no longer necessary to treat them as raw HTML in Twig.
=> Always HTML-escape error messages

src/Controller/ExportController.php, src/FontProvider.php, src/Generator/EpubGenerator.php, templates/export.html.twig, tests/FontProviderTest.php
The existing font family name handling wasn't taking into account
the fact that fc-list reports these with alternate names appearing
after a comma. This removes this trailing info, and also adds more
thorough weight and slant handling.
The dropdown list is also updated to include all available fonts,
because it sounds like at some point we'll update this to be more
responsive and useful but for now this makes it much easier to
test and see what is available.
Bug: T261479
=> Update font-handling for better selection, weights, etc.

src/Command/ExportCommand.php
Add total duration and peak memory usage to the success message
shown when creating an ebook on the command line. This gives
a convenient way to compare generation of different books, and
will help when developing caching etc.
=> Add time and memory usage to CLI output

src/PageParser.php
Remove the 'data-mw' attribute that is included in different DOM
elements.
=> Remove data-mw attributes from books

README.md, docker/Dockerfile, docker/docker-compose.yml, docker/php.ini
Xdebug v3 triggers an exception on symfony di when compiling. This only
fails when calling app:install and cache:clear (afaik)
After the initial setup, xdebug can be enabled if needed and works as
expected unless you need to recompile the container.
Also in this patch
* Move configs to be mounted instead of copied at build time
* Upgrade xdebug config to work with v3
=> Disable xdebug by default

src/Command/ExportCommand.php, src/Controller/ExportController.php, src/Exception/WSExportInvalidArgumentException.php, src/GeneratorSelector.php, tests/Book/GeneratorSelectorTest.php, tests/Http/BookTest.php
Avoid blank format param in ExportController and use a 404
exception instead of 500 for invalid format names.
Bug: T269343
=> Validate URL 'format' parameter

src/Generator/EpubGenerator.php
Apple Books requires this file for embedded fonts.
See https://help.apple.com/itc/booksassetguide/en.lproj/static.html#itc2cf4d26eb
also https://www.mobileread.com/forums/showthread.php?t=192389
Works on my local macOS and iOS:
Use case: I uses embed font to support characters in the Unicode SIP Plane.
=> fix: support font embedding in Apple iBooks

src/BookProvider.php, src/Refresh.php, src/Util/Api.php, tests/Book/BookProviderTest.php, tests/Book/RefreshTest.php, tests/Util/ApiTest.php
Remove the manual caching of namespaces, and instead use standard
Symfony caching in the Api class, along with a runtime variable
to avoid multiple calls to the filesystem.
Bug: T265660
=> Cache namespaces for 1 month

migrations/Version20201222094802.php, src/Controller/ExportController.php, src/Entity/GeneratedBook.php, tests/Http/BookTest.php
Add a new 'duration' column to the DB table, to record the number
of seconds each book generation took.
Bug: T267079
=> Record book generation duration

composer.json, composer.lock
The commit e5b2214c3ce3df1ad0314fb9090183525c569568 adds use of
the symfony/stopwatch library, but added it as a dev dependency.
This doesn't matter because another prod requirement,
symfony/migrations also uses this
library, but we should list it as an explicit prod requirement
anyway.
Bug: T267079
=> Add stopwatch as a prod dependency

src/Controller/ExportController.php
> GNU FreeFont implements [...] aside from the very large CJK Asian character set.
https://en.wikipedia.org/wiki/GNU_FreeFont
Context: https://github.com/wsexport/tool/pull/296#issuecomment-748816532
=> fix: do not provide free serif to zh/jp/kr

src/BookProvider.php
There's a bug in the Guzzle cache middleware that means we have
to switch to saving the file responses (for images) in the response
handler rather than leaving it to Guzzle.
This is a workaround until the bug is fixed.
Bug: T265660
=> Stop using Guzzle's 'sink' option

src/Controller/ExportController.php, tests/Http/BookTest.php
This makes it slightly confusing: we'll now have 'page' and 'title',
with the former triggering the export and the latter filling the
form field, but this is probably acceptable for the sake of URL
maintenance.
Bug: T256345
=> Add new ?title= URL param to prefill title

src/BookProvider.php, src/Page.php, tests/Book/BookProviderTest.php
We were encoding HTML entities when storing the metadata in the
Book object, and then again when writing to HTML.
A few other tweaks to docblocks also, to make it a bit clearer what
things mean.
Bug: T270495
=> Don't encode HTML entities before use

src/Controller/ExportController.php
Remove underscores and uppercase the first character of the 'title'
parameter, falling back to 'page' if there's no title.
Bug: T256345
=> Normalize the ?title= parameter

src/PageParser.php, tests/Book/PageParserTest.php
align attributes were being converted to text-align:center
but should be modifying margins for tables.
Bug: T270807
=> Add special handling for table align attributes

src/Controller/ExportController.php, src/Generator/EpubGenerator.php, src/Refresh.php, src/Util/Api.php, src/Util/Util.php, tests/Book/RefreshTest.php, tests/Util/ApiTest.php
Switch from manually storing the about pages in files, to using
Symfony cache with a TTL of 1 month.
Bug: T271876
=> Cache 'about' page with app cache

docker/docker-compose.yml
Add `host.docker.internal` to docker so the container can resolve to host
machine's IP address.
=> Add host `host.docker.internal` to docker

templates/export.html.twig, tests/Http/BookTest.php
Just use normal HTML variable escaping (which does take care of
quotation marks, and doesn't fail with an error for invalid
strings as shown in the bug).
Bug: T272181
=> Remove attribute escaping from title

src/PageParser.php, tests/Book/PageParserTest.php
The existing system was still creating duplicates where there were
no ascii characters in the original ID (they were all replaced by
underscores, so only had to match on the length).
Also switched from appending a count of each duplicate ID to just
using a count of all IDs in order to create a unique ID, because
array_count_values() isn't very fast and we don't actually care
about this number.
Bug: T272119
=> Transliterate element IDs and fix replacement process

src/PageParser.php, src/Util/Util.php, tests/Book/PageParserTest.php
If a work doesn't use ws-summary, we look for all anchors containing
the work's title. This search wasn't being done with a URL-encoded
string.
Also fix an overloaded variable ($title → $linkTitle).
Bug: T270367
=> Escape href value when searching for subpages

src/Util/Api.php
Add special handling for the one Wikisource whose language code
doesn't match its subdomain.
Bug: https://phabricator.wikimedia.org/T272043
=> Override for 'nan' language code → 'zh-min-nan'

src/PageParser.php, tests/Book/PageParserTest.php
When processing img elements, this was replacing figure and
figure-inline with an img element. This was discarding any
figcaption or other contents of the node.
It doesn't look like there's any reason to do this replacement,
as we're already modifying the img element to our requirements.
Also switch to ctype_xdigit to check for the thumb URL segments
being valid hex digits, because using is_numeric to do this was
deprecated as of PHP 7.0.
Also check for any contained img elements in figure etc. and break
if none found.
Bug: https://phabricator.wikimedia.org/T272307
Bug: https://phabricator.wikimedia.org/T272180
=> Don't remove child nodes of figures and images.

src/BookProvider.php, src/PageParser.php, src/Util/Api.php, src/Util/Util.php, tests/Util/ApiTest.php
I'm unsure about the repercussions of changing how we load the html
content from XML to HTML but the later seems to fix this issue. It
is also how we load pages' content from parsoid.
This issue was happening becuase `$this->xPath->query( '//html:a[contains(@style, "mw-Ref")]' )`
was not working when the DOMDocument content was loaded via loadHTML.
Removing the namespace from the above query fixes the book references but breaks the About
page unless it is loaded as HTML.
Bug: T270372
=> Fix references sometimes opening as external links

config/bootstrap.php, config/services.yaml, src/Generator/ConvertGenerator.php, src/GeneratorSelector.php, tests/Book/GeneratorSelectorTest.php, tests/BookCreator/BookCreatorIntegrationTest.php
Inject the timeout value instead of retrieving it from a global
variable. This isn't the cleanest way to implement this, because
it perpetuates the statefulness of ConvertGenerator, but it
isn't any worse than the existing code!
Bug: https://phabricator.wikimedia.org/T265854
=> Remove exec-timeout global variable

src/Repository/CreditRepository.php
Otherwise the connection can stay open for the entire time the book is
being exported, making us vulnerable of hitting our concurrent
connection limit.
=> CreditRepository: Close connection as soon as query finishes

i18n/en.json, i18n/qqq.json, src/Controller/ExportController.php, src/Generator/ConvertGenerator.php, src/Generator/EpubGenerator.php, src/GeneratorSelector.php, templates/export.html.twig, tests/Book/GeneratorSelectorTest.php, tests/BookCreator/BookCreatorIntegrationTest.php
Add option that will exclude/include credits in exported books.
Bug: T274959
=> Create option to disable credits in export form

src/PageParser.php
Add urldecode to names in credit repository queries so that it decodes
any urlencoded characters.
Bug: T257886
=> Add urldecode to images and pages names in credit repo

i18n/en.json, i18n/qqq.json, src/Controller/ExportController.php, src/FontProvider.php, src/Util/OnWikiConfig.php, templates/export.html.twig, tests/Book/GeneratorSelectorTest.php, tests/BookCreator/BookCreatorIntegrationTest.php, tests/FontProviderTest.php, tests/Http/BookTest.php, tests/Util/OnWikiConfigTest.php
Set up an on-wiki config page MediaWiki:WS_Export.json, which
can be used to store any per-Wikisource configuration. So far
this is just `defaultFont` but it can be extended as needed.
Defaults for these configs live in the tool's code, not in
Multilingual Wikisource (like the About page) because that wiki
will need its own config.
The existing default of FreeSerif will need to be migrated to
the on-wiki config once this change has been merged.
Bug: https://phabricator.wikimedia.org/T274561
=> Add on-wiki config to define default fonts

i18n/en.json, i18n/qqq.json, src/Exception/WsExportException.php, src/Generator/ConvertGenerator.php, src/Repository/CreditRepository.php, src/Util/Api.php, templates/export.html.twig
This covers errors thrown when doing format conversions, MySQL timeout
and max_user_connections errors.
This also hides the 'Learn more' link for 404 errors since re-trying
won't help in that case.
Bug: https://phabricator.wikimedia.org/T278189
=> Further improve handling of common errors

src/PageParser.php, tests/Book/PageParserTest.php
Refactor logic to always check if image's url is `ctype_xdigit` when
creating the picture objects.
Bug: T257886
=> Refactor parsing picture in PageParser::getPicturesList()

src/Util/Api.php, src/Util/OnWikiConfig.php, src/Util/Util.php
This prevents InvalidArgumentExceptions that happen from erroneous user
input for the lang= parameter.
=> Sanitize cache keys

public/styles.css
Bug: https://phabricator.wikimedia.org/T277820
=> Reduce width of form and fix label font sizes

src/Page.php, src/PageParser.php, tests/Book/PageParserTest.php
This changes the chapter subpage finding logic (when there's no
ws-summary in use) to use the links' title attribute rather than
their href attribute. It also moves the prefix-searching out of
XPath and into the link loop.
Bug: https://phabricator.wikimedia.org/T275870
=> Improve subpage-finding to not use URLs

src/PageParser.php
These are not valid in EPUBs.
Bug: https://phabricator.wikimedia.org/T272819
=> Remove `mw:Extension` link elements

public/robots.txt
For whatever reason bots tend to ignore this (even the good bots), but
it doesn't hurt to have it.
=> Add robots.txt disallowing all bots

src/Generator/ConvertGenerator.php
It's no longer being configured, and getting rid of it removes
one of the remaining global config variables.
Bug: https://phabricator.wikimedia.org/T265854
=> Remove configurability of ebook-convert CLI command

src/Generator/ConvertGenerator.php, src/Generator/EpubGenerator.php, src/GeneratorSelector.php, src/Refresh.php, tests/Book/GeneratorSelectorTest.php, tests/Book/RefreshTest.php, tests/BookCreator/BookCreatorIntegrationTest.php
This switches the caching, but doesn't fully clean up a few other
things; they'll come in a later patch.
Bug: https://phabricator.wikimedia.org/T273832
=> Use Symfony caching for CSS, rather than FileCache

README.md, docker/docker-compose.yml
If you have another server on port 8888, this allows
you to set WS_EXPORT_PORT in .env and change the WS Export
server port.
=> Docker: allow configuration of port

src/Wikidata.php, tests/WikidataTest.php
Change the language list to use localized names for Wikisources,
falling back to the user's interface language where possible and
then to English if there's no other label (all Wikisource's have
English labels on Wikidata).
Bug: https://phabricator.wikimedia.org/T276891
=> Use local langs for Wikisource names

composer.json, composer.lock, symfony.lock
`composer update` wouldn't run due to incompatibilities. This PR bumps all symfony packages to 5.3 and updates the locked dependencies to the new versions.
=> Bump symfony deps to 5.3.*

templates/export.html.twig
HTML-escape all parameters to exceptions, when they're displayed
on the export page.
Bug: https://phabricator.wikimedia.org/T290674
=> Escape exception parameters on display

src/Repository/GeneratedBookRepository.php, tests/Repository/GeneratedBookRepositoryTest.php
This is to avoid confusion because MySQL casts a string starting
with a number to that number, when comparing to the output of MONTH()
etc.
Bug: https://phabricator.wikimedia.org/T290674
=> Avoid non-numeric year and months for stats query

src/PageParser.php
These have no purpose in epubs and cause validation failures.
Bug: T287548
=> Strip mw:PageProp meta tags

src/Controller/ExportController.php, templates/export.html.twig
We already know that we don't want to link to a lang if it's not set, so this just makes it more specific. It must be set and must exist in the area of existing wiki langs.
=> Don't link to non-existent wiki lang

src/Generator/AtomGenerator.php
DOMDocument::createElement escapes '<' and '>' but not '&'...
=> Atom: Makes sure to escape '&'

src/Generator/AtomGenerator.php
Let's rely on the std functions instead of hacking ours.
=> AtomGenerator: use native XML escape

public/toolinfo.json
These names were the result of the following command:
git log --format='{"name": "%aN"},' | sort |  uniq -c | sort -nr
=> Add missing author names to toolinfo.json

composer.json, composer.lock
We can't go to 6.0 (or 6.1 as it's up to now) because we still
need to work on PHP 7.3.
Bug: https://phabricator.wikimedia.org/T311024
=> Upgrade to Symfony 5.4

.github/workflows/ci.yml, README.md, docker/Dockerfile, tests/FontProviderTest.php
Per request on the French Wikisource, it was asked that WSExport had a dyslexic-friendly font (see https://fr.wikisource.org/wiki/Wikisource:Scriptorium/Mars_2023#Police_pour_dyslexique_en_export). I thus added OpenDyslexic to the requirements and updated the tests and documentation to mirror this.
=> Add OpenDyslexic font

src/Wikidata.php
Modify the query to ignore Wikisources that are instances of "closed wiki".
Bug: https://phabricator.wikimedia.org/T276887
=> Remove closed Wikisources from language dropdown

src/Util/Util.php, tests/Util/UtilTest.php
- Add more tests for Util::encodeString, to improve confidence that the new implementation doesn't break the old behavior
- Fix [T332112](https://phabricator.wikimedia.org/T332112): replace deprecated function mb_convert_encoding() with iconv()
=> Fix T332112: replace deprecated function mb_convert_encoding()

bin/console, composer.json
phpcs doesn't handle extensionless files unless we want to check all, but it does support stdin so this just adds a separate command for testing this one file.
=> Apply coding standards to bin/console

.github/workflows/ci.yml
For installing Calibre in CI, and getting tests to pass.
=> Add libxcb-cursor0 for Calibre

src/Util/Util.php, tests/Book/PageParserTest.php
This avoids the deprecated mb_convert_encoding usage, as well as
the encoding of characters in non-HTML contexts.
Bug: T271390
=> Simplify loading of HTML

src/Generator/ConvertGenerator.php, tests/Book/GeneratorSelectorTest.php, tests/BookCreator/BookCreatorIntegrationTest.php
To avoid the latter having to instantiate an EpubGenerator and to simplify the constructor.
=> Inject EpubGenerator into ConvertGenerator

i18n/en.json, i18n/qqq.json, public/styles.css, templates/_month_year_selector.html.twig, templates/base.html.twig, templates/export.html.twig, templates/statistics.html.twig
Redesign stats page to be cleaner and
convey stats in a better way with more
accessibility for year/month inputs.
Also added i18n for content on the page.
Bug: [T353737](https://phabricator.wikimedia.org/T353737)
=> Redesign stats page

src/PageParser.php, tests/Book/PageParserTest.php
This fixes two issues with the PageParser::cleanReferenceLinks() method: the first when there are no reference links found, the second the actual bug linked below. The `typeof` attribute can contain values other than 'mw:Extension/ref' but we were only checking for that one on its own. Switching to xPath contains() function fixes this.
Bug: T358965
=> Fix issue with cleaning transcluded reference links

src/BookProvider.php, src/PageParser.php, tests/Book/BookProviderTest.php
Add the domain name to image src values that don't have one, to support WikiHiero. Also move the protocol-relative handling out of the PageParser so that it can go along with the new domain name adding in one place.
Bug: T354242
=> Handle unqualified image src attrs

src/BookProvider.php, tests/Cli/BookCliTest.php
The change I made in #513 fixed the URLs after they were used
to fetch the images! This moves that same logic to the location
in which it'll actually work. Sorry for the noise!
Bug: T354242
=> Move image URL fixing to where the URL is used

src/BookProvider.php
Because shared-repo images are reported as missing, do not check for that status. And to make things simpler, use the same handling for invalid ones as well, and just check to see if any imageinfo metadata has been returned (that's all we're interested in, after all).
This is a follow-up to GH #512.
Bug: T372956
=> Check for imageinfo rather than missing or invalid

public/index.php
Remove a deprecated and removed constant.
Bug: T384115
=> Remove Request::HEADER_X_FORWARDED_ALL

src/Util/Util.php
Sometimes generated files (PDFs etc) are removed by another process before the code in ConvertGenerator::create() is run. This adds a check, to avoid trying to remove non-existent files.
Bug: T387239
=> Do not try to remove non-existent files

i18n/en.json, i18n/qqq.json, public/styles.css, templates/base.html.twig
Add a language-switching dropdown menu in the site footer.
Bug: T387426
=> Add language switcher
