book/i18n.ini

See discussion on en.wikisource.org
https://en.wikisource.org/wiki/Wikisource:Scriptorium#Kindle_users:_Please_check_mobi_export_form

Fix grammar

---

cli/book.php

- arguments are actually required, not optional
- move generator creation into method
- fail early if format is not known, before downloading anything

Fix argument parsing

---

Makefile
README.md
cli/book.php
composer.json
tests/cli/BookIntegrationTest.php
tests/cli/BookTest.php

* refactored book cli to be testable
* added basic integration tests for various formats
* updated docs

Added support for tests

---

book/Refresh.php
http/book.php
tests/book/RefreshTest.php
tests/utils/ApiTest.php
tests/utils/UtilsTest.php
utils/Api.php
utils/utils.php

+ some required refactoring to make the code testable

Unit tests for Refresh and Api

---

.travis.yml
Makefile
tests/cli/BookIntegrationTest.php

This PR integrates [epubcheck](https://github.com/IDPF/epubcheck) into the build pipeline. Errors flagged by epubcheck currently don't fail the build.

Run epubcheck and display warnings

---

book/init.php
cli/book.php
composer.json
tests/utils/LoggingMiddlewareTest.php
tests/utils/ToolLoggerTest.php
utils/Api.php
utils/LoggingMiddleware.php
utils/ToolLogger.php

This PR adds logging to all outgoing requests + adds the necessary logging structure.

Log all outgoing HTTP requests in debug mode

---

book/PageParser.php
tests/book/BookProviderTest.php
tests/book/PageParserTest.php
tests/book/fixtures/Pacotilha_poetica/Se_namora_por_gosto_ou_por_precisão.html

PageParser: urldecode page titles

---

book/BookCreator.php
book/CreationLog.php
book/GeneratorSelector.php
book/init.php
cli/book.php
http/book.php
http/stat.php
http/templates/book.php
http/templates/stat.php
tests/book/BookCreatorIntegrationTest.php
tests/book/BookCreatorTest.php
tests/book/BookProviderTest.php
tests/book/GeneratorSelectorTest.php
tests/book/PageParserTest.php
tests/book/RefreshTest.php
tests/cli/BookCliTest.php
tests/http/BookTest.php
tests/http/StatTest.php
tests/test_init.php
tests/utils/ApiTest.php
tests/utils/LoggingMiddlewareTest.php
tests/utils/ToolLoggerTest.php

- add more tests (+ request tests)
- book creation is now centralised in one place, removed duplication cli <-> http

Prepare for caching (#38)

---

.gitignore
composer.json

This adds some missing dependencies to composer.json
and adds the temp directory to the repo so that developers don't
have to create it manually.

Add missing dependencies

---

utils/Api.php

PHP Notice:  Undefined variable: title in /mnt/nfs/labstore-secondary-tools-project/wsexport/tool/utils/Api.php on line 183

Api: fix PHP warning

---

utils/Api.php

Bug: https://phabricator.wikimedia.org/T221336

Fix "Undefined index: pages in Api.php"

---

http/toolinfo.json

Add some extra keywords and change the title to match what
was in a toolinfo.json in the tool's home directory.

Add to toolinfo.json

---

composer.json
composer.lock
http/book.php
phpcs.xml
tests/utils/ApiTest.php
utils/Api.php
utils/utils.php

Bug: https://phabricator.wikimedia.org/T222932

Handle Wikimedia server errors nicely

---

src/BookProvider.php

Currently, on some pages, batches of 50 page titles requested from
phetools exceed the maximum header length, causing failures.
Address it by adaptively forming batches that are guaranteed to fit.
The limit was experimentally determined to be a bit under 4000 bytes,
so giving each batch 3000 bytes to fit into.
Testing: https://en.wikisource.org/wiki/Foster%27s_Russian_bank

Fix credits retireval

---

src/BookProvider.php

Also, remove error suppression that was inadvertently broken before -
better fix problems as they appear instead of randomly having no
credits. Hopefully, with URLs not being too long anymore suppression
will not be needed.

Convert another instance of overly long URLs during credits retrieval

---

public/book.php
src/Util/Util.php

Support more posssible situations that can result in an error,
and properly handle errors from non-production servers (i.e.
PheTools).

Handle more HTTP errors

---

src/BookProvider.php
src/FontProvider.php
src/Generator/EpubGenerator.php
src/Util/Api.php
src/Util/LoggingMiddleware.php
src/Util/Util.php

Mostly documentation, but also a couple instances of invalid function names.

Fix a few things IDEA complained about

---

composer.json
composer.lock
phpcs.xml
src/Generator/ConvertGenerator.php
src/Util/Util.php
tests/BookCreator/BookCreatorIntegrationTest.php
tests/cli/BookCliTest.php

I was about to add a new exec() call but realised that it would
be nice to shift to an easier to use (and not prohibited by phpcs)
system of external process-running.
https://phabricator.wikimedia.org/T226790

Use symfony/process to run external commands

---

src/BookProvider.php
src/Util/Api.php

https://phabricator.wikimedia.org/T225686

Use request pool to limit concurrent image requests

---

config.dist.php
src/Generator/ConvertGenerator.php

Increase exec timeout to 120s

---

tests/BookCreator/BookCreatorIntegrationTest.php

Check whether java is installed before running epubcheck tests.

Actually check for Java

---

.travis.yml
README.md
bin/import.php
bin/install.php
config.dist.php
src/CreationLog.php
tests/CreationLogTest.php
tests/http/BookTest.php
tests/http/StatTest.php

* Add tests for logging class.
* Create import tool for Sqlite →  MariaDB.
* Documentation (note that bin/install.php needs to be run)
Refs #173
Bug: https://phabricator.wikimedia.org/T226070

Move logs to MariaDB

---

public/templates/book.php
src/CreationLog.php

Add Wikisource link to recently popular list

---

.travis.yml

Allows to have newer dependencies closer to the one on ToolForge

Uses Ubuntu Bionic for Travis builds

---

public/templates/header.php
tests/http/BookTest.php

Add a descriptive title to the page, for greater clarity and to
avoid the Scunthorpe problem.

Expand page title

---

src/Util/Api.php

Escape lang input

---

README.md
public/templates/book.php
public/templates/stat.php

Improve performance by moving expensive DB query that diplays some stats
to the statistics page (stats.php).
Bug: T236391
Bug: T237029

Move query that display stats in home page to statistics page

---

src/Cleaner/BookCleanerEpub.php
src/PageParser.php

* Moves body <style> to the <head> node and make sure it's used on all splits of a file.
* Makes sure that <body> attributes are preserved during split
Closes #210

Makes sure that templatestyles are properly used

---

src/PageParser.php

Drop TemplateStyles link elements from chapter bodies

---

src/Generator/EpubGenerator.php

Simplifies also its code.
This allow the title page to fit in one page in PDF A5 even if the work title spreads on two lines.
Closes #216

Makes ePub title page smaller

---

src/Generator/Epub2Generator.php
src/Generator/Epub3Generator.php
src/Generator/EpubGenerator.php

Uses just a plain image as cover

---

public/templates/footer.html

Add links to the project's Phabricator workboard
and new-issue form.
https://phabricator.wikimedia.org/T255512
Bug: T255512

Change issue link from GitHub to Phabricator

---

.gitignore
Dockerfile
README.md
docker-compose.yml
docker/000-default.conf
docker/ports.conf

Everything seems to work except for integration tests. I might need some help with that.
Apache config can be changed to remove "/public/" from the path
Not sure what else I could be missing

Add docker dev environment

---

src/Generator/EpubGenerator.php

Task: https://phabricator.wikimedia.org/T264524

Do not include cover images if the "include images" option is disabled

---

composer.json
composer.lock
src/Generator/EpubGenerator.php

Switch to i18n-friendly long date format for cover

---

src/Controller/ExportController.php

For backwards compatibility for old Toolforge links.
Bug: T263577

Add /tool/book.php as a alternative URL

---

composer.json
composer.lock
tests/BookCreator/BookCreatorIntegrationTest.php

Update to the latest MediaWiki coding standards, and other
PHP dependencies.

Update code sniffer and other deps

---

.github/workflows/ci.yml
docker/Dockerfile
tests/FontProviderTest.php

Bump Docker and CI PHP versions

---

bin/opds.php
phpcs.xml
src/BookCreator.php
src/BookProvider.php
src/Controller/ExportController.php
src/OpdsBuilder.php
src/Refresh.php
src/Util/Api.php
src/Util/Util.php
tests/Book/BookProviderTest.php
tests/Book/RefreshTest.php
tests/Http/BookTest.php
tests/Util/ApiTest.php

Move the method dealing with getting the lang from the request
into a controller, and add new accessor method to Api class. This
is a step towards making the Api class into a service.
Bug: T265660

Refactor Api::$lang

---

tests/BookCreator/BookCreatorIntegrationTest.php

Add the mobi integration test to CI, because it's not like the
epubcheck tests that usually fail.

Run more tests in CI

---

src/Refresh.php
src/Util/Api.php

Make $domainName variable in Api class private and add getDomainName
method to make its value accessible.

Make Api::$domainName private

---

composer.lock

Mainly needed for toolforge-bundle updated deploy script

Upgrade composer packages

---

.env
config/packages/prod/monolog.yaml

Add a new environment variable with which to change the subject
prefix of the emails sent when an error is logged.
Bug: T266849

Add log email subject env var 

---

composer.json
composer.lock
symfony.lock

Needed to see timing events on symfony profiler

Add symfony/stopwatch as a dev requirement

---

src/BookProvider.php
tests/Book/BookProviderTest.php

phetools.toolforge.org returns a 308

Fix phetools

---

src/Generator/EpubGenerator.php

Add stylesheet to title page

---

composer.json
composer.lock
src/Command/ExportCommand.php
src/Controller/ExportController.php
src/Util/Api.php
symfony.lock
templates/export.html.twig
tests/Book/BookProviderTest.php
tests/Book/RefreshTest.php
tests/Util/ApiTest.php

Add caching to API calls and other URL-fetching, and an HTTP
cache as well. Also add a means to bypass this for web and CLI
export requests.
Bug: T265660

Add caching to the API

---

src/Generator/ConvertGenerator.php

Some books take a very long time to convert to PDF. --enable-heuristics
speeds this process significantly
See: https://manual.calibre-ebook.com/conversion.html#heuristic-processing

Enable heuristic processing for ebook-convert

---

src/Generator/ConvertGenerator.php

Reverts wsexport/tool#297
See: https://phabricator.wikimedia.org/T271220

Revert "Enable heuristic processing for ebook-convert"

---

src/Cleaner/BookCleanerEpub.php
src/PageParser.php
tests/Book/PageParserTest.php

Normalize element IDs to avoid duplicates or invalid IDs

---

src/Command/ExportCommand.php
src/Controller/ExportController.php
src/GeneratorSelector.php
tests/Http/BookTest.php

Also move all format alias handling into one place, in the
controller.
Bug: T271474

Restore 'epub' alias for 'epub-3'

---

src/GeneratorSelector.php
tests/Http/BookTest.php

Add 'pdf' as an alias for 'pdf-a5'.
Bug: T269726

Add PDF alias

---

README.md

README: instruct to run all migrations, not just creating the db

---

templates/base.html.twig

Add version number to footer

---

.env
config/services.yaml
src/Command/ExportCommand.php
src/Controller/ExportController.php
templates/export.html.twig

Add APP_ENABLE_CACHE environment variable, defaulting to false,
to enable caching of API requests.
Bug: T271771

Add feature flag for caching

---

src/PageParser.php
tests/Book/fixtures/Tales_of_Unrest/Navigation.html

Exclude interwiki links from chapter lists

---

src/Util/Api.php

Because the page parsing process looks at element IDs over all
documents, it's necessary to re-do it on every book generation,
otherwise there's the risk of getting duplicate IDs in that
page.
Bug: T268000

Parse About page config after caching, not before

---

README.md
src/Command/OpdsCommand.php

Bug: https://phabricator.wikimedia.org/T266579

Update URLs etc. to new name: ws-export

---

templates/base.html.twig

Add lang and dir params to `<html>`, and fix column display.
Bug: T274957

Fix for RTL display

---

config/services.yaml
src/Util/Api.php
src/Wikidata.php

Follow-up: https://github.com/wikimedia/ws-export/pull/334

Inject ClientInterface

---

.gitignore
.phan/baseline.php
.phan/config.php
composer.json
composer.lock
phpcs.xml
src/Controller/ExportController.php
src/Wikidata.php
symfony.lock

Bug: https://phabricator.wikimedia.org/T276519

Add Phan analysis

---

src/PageParser.php

* Remove Parsoid-style ID attributes.
* Move fragment substring checking into PHP instead of XPath, where it's quicker.
Bug: https://phabricator.wikimedia.org/T272119

Improve ID parsing

---

.env
README.md
config/packages/doctrine.yaml
config/services_test.yaml
src/BookCreator.php
src/BookProvider.php
src/Command/CheckCommand.php
src/Command/ExportCommand.php
src/Command/OpdsCommand.php
src/Controller/ExportController.php
src/Generator/EpubGenerator.php
src/Repository/CreditRepository.php
src/Util/Api.php
tests/Book/BookProviderTest.php
tests/BookCreator/BookCreatorIntegrationTest.php
tests/Cli/BookCliTest.php
tests/Http/BookTest.php

Remove credits phetools api dependency by quering the corresponding tables to
get the book credits directly in ws export.
Bug: T257886

Remove phetools dependency

---

src/BookProvider.php
src/Repository/CreditRepository.php

Noticed this in IntelliJ when debugging the issue we thought we had with the credits.

BookProvider: remove unused code

---

src/Controller/ExportController.php

We sometimes hit the max_user_connections error when writing to
tools-db. Since this tracking isn't critical, we silently ignore to
still allow the book to be downloaded.

ExportController: capture errors writing to tools-db

---

i18n/en.json
i18n/qqq.json
public/styles.css
templates/export.html.twig

Also add missing message.
Bug: https://phabricator.wikimedia.org/T277820

Fix layout of 'back to Wikisource' button

---

i18n/en.json

Bug: https://phabricator.wikimedia.org/T277820

Update title help text

---

src/Util/Api.php

Bug: https://phabricator.wikimedia.org/T259687

Remove Wikilivres

---

src/Controller/ExportController.php
tests/Http/BookTest.php

Restrict allowed characters in the lang parameter.
Bug: T290674

Sanitize lang URL parameter

---

src/Cleaner/BookCleanerEpub.php

Useful for old reading software like Adobe versions before 2009.
Should be ok now hopefully with moderns reading systems.
Bug: T261238

Drops the HTML file splitting hack

---

src/BookProvider.php

Currently, non-Djvu/Pdf covers use the full size of the image
specified. This can be very large, much larger than the book
itself.
This commit instead limits the cover size to 400px (or the image
size, if smaller).
It also avoids hardcoding assumptions about the thumbnail URL
and instead uses the 'thumburl' field.
It also adds better defence against bad page numbers (and defaults
to 1 in that case), as well as defence against a non-JPG thumbnail
for a DjVu/PDF file.
This does mean there are two requests to get the cover, as it's
not possible to tell the image mime type and max size and get
the appropiate thumbnail in a single request.
Bug: T286389

Limit the size of book covers

---

src/EventSubscriber/RateLimitSubscriber.php

RateLimitSubscriber: check if user is logged in

---

README.md
bin/console
composer.json
composer.lock
symfony.lock

Auto-generate the CLI usage docs from the `app:` namespace Commands.

Add 'CLI Usage' section to README.md

---

src/BookProvider.php

Books define their cover image via a ws-cover microformat, and
there's no guarantee that they'll do so correctly. This change
moves this checking logic into the getCover method and makes
sure it'll fail gracefully if the cover image doesn't exist
(rather than failng to generate the whole book).
Bug: T240363

Guard against cover image not existing

---

README.md
docker/Dockerfile
package-lock.json

Remove OSTYPE check in Dockerfile since it is not
necessary. Its value is empty when image is being built.
Cleaned up commands in README file.

Remove OSTYPE check and update README file

---

config/packages/framework.yaml
config/packages/test/framework.yaml
src/Controller/ExportController.php
src/EventSubscriber/RateLimitSubscriber.php

* Avoid passing null to preg_replace() and str_replace().
* Remove deprecated Session and use RequestStack instead.

Fix up deprecations

---

.env

Default APP_ENV to prod instead of dev

---

resources/styles/mediawiki.css

Add Parsoid alignment styles to default stylesheet

---

docker/Dockerfile

They are required by epubcheck.

Add libegl1 and libopengl0 libraries to Dockerfile

---

README.md

Various small fixes to the README in #471 to make `markdownlint` (and me) happy :)

Apply markdownlink fixes to README

---

.github/workflows/ci.yml

This is something we've added to other repos that do things such as auto-creation of CLI docs (as done here) or built assets (which we don't do here).

Add check to CI to ensure no files are changed

---

src/PageParser.php

These do not pass epubcheck validation.

Remove meta tags of type NoInclude

---

.github/workflows/ci.yml

Add epubcheck version to test matrix:
```
epubcheck: [ '4.2.4', '5.0.0' ]
```
as a step towards upgrading to 5.0.0
Bug: [T327608](https://phabricator.wikimedia.org/T327608)

Move epubcheck version to a variable

---

src/BookProvider.php

To avoid errors when working with TIFF cover images.
Bug: T353954

Add iiurlwidth API param when fetching cover image info

---

src/BookProvider.php

To avoid a 2nd API request, always use 400px for the image width, and use the file extension to determine if the file is PDF/DjVu.

Make only one API request for cover image info

---

README.md
config/services.yaml
src/Generator/ConvertGenerator.php
src/Util/Semaphore/Semaphore.php
src/Util/Semaphore/SemaphoreHandle.php
src/Util/Semaphore/UnixSemaphore.php
src/Util/Semaphore/UnixSemaphoreHandle.php
tests/Util/Semaphore/UnixSemaphoreTest.php

Sadly these semaphores don't work on Windows

Uses a UNIX semaphore to limit concurrent ebook-convert calls

---

README.md

Update README.md to add more links

---

.github/workflows/ci.yml
src/EpubCheck/EpubCheck.php

Also check that the file exists so that it fails if epubcheck is not installed.

Update epubcheck to v5.2.1

---

composer.json
composer.lock

Update remaining PHP dependencies
